// <auto-generated />
using System;
using LorcanaCardCollector.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LorcanaCardCollector.Migrations
{
    [DbContext(typeof(CardsContext))]
    [Migration("20251128235921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LorcanaCardCollector.Models.Cards", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Franchise")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GemColor")
                        .HasColumnType("int");

                    b.Property<string>("Image_URL")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("Image_URL");

                    b.Property<int?>("Ink")
                        .HasColumnType("int");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Strength")
                        .HasColumnType("int");

                    b.Property<int?>("Willpower")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = "ARI-003",
                            CardName = "King Stefan - New Father",
                            Franchise = "Sleeping Beauty",
                            GemColor = 0,
                            Image_URL = "https://lorcana-api.com/images/king_stefan/new_father/king_stefan-new_father-large.png",
                            Ink = 5,
                            SetName = "Archazia's Island"
                        },
                        new
                        {
                            CardId = "ARI-001",
                            CardName = "Rhino - Motivational Speaker",
                            Franchise = "Bolt",
                            GemColor = 10,
                            Image_URL = "https://lorcana-api.com/images/rhino/motivational_speaker/rhino-motivational_speaker-large.png",
                            Ink = 5,
                            SetName = "Archazia's Island"
                        },
                        new
                        {
                            CardId = "ARI-002",
                            CardName = "Perdita - Playful Mother",
                            Franchise = "101 Dalmatians",
                            GemColor = 9,
                            Image_URL = "https://lorcana-api.com/images/perdita/playful_mother/perdita-playful_mother-large.png",
                            Ink = 4,
                            SetName = "Archazia's Island"
                        });
                });

            modelBuilder.Entity("LorcanaCardCollector.Models.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeckId"));

                    b.Property<string>("AccessKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeckDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeckName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DeckId");

                    b.ToTable("Decks");

                    b.HasData(
                        new
                        {
                            DeckId = 1,
                            AccessKey = "SeedDeck",
                            DeckDescription = "Seed data for the deck",
                            DeckName = "Seed Deck"
                        });
                });

            modelBuilder.Entity("LorcanaCardCollector.Models.DeckCard", b =>
                {
                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuantityInDeck")
                        .HasColumnType("int");

                    b.HasKey("DeckId", "CardId");

                    b.HasIndex("CardId");

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("LorcanaCardCollector.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("CardId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            CardId = "ARI-003",
                            Cost = 0.59m,
                            Price = 1.99m,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("LorcanaCardCollector.Models.DeckCard", b =>
                {
                    b.HasOne("LorcanaCardCollector.Models.Cards", "Card")
                        .WithMany("DeckCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LorcanaCardCollector.Models.Deck", "Deck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("LorcanaCardCollector.Models.Inventory", b =>
                {
                    b.HasOne("LorcanaCardCollector.Models.Cards", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("LorcanaCardCollector.Models.Cards", b =>
                {
                    b.Navigation("DeckCards");
                });

            modelBuilder.Entity("LorcanaCardCollector.Models.Deck", b =>
                {
                    b.Navigation("DeckCards");
                });
#pragma warning restore 612, 618
        }
    }
}
