// <auto-generated />
using System;
using LorcanaCardCollector.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LorcanaCardCollector.Migrations
{
    [DbContext(typeof(CardsContext))]
    partial class CardsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LorcanaCardCollector.Models.Cards", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Franchise")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GemColor")
                        .HasColumnType("int");

                    b.Property<string>("Image_URL")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("Image_URL");

                    b.Property<int?>("Ink")
                        .HasColumnType("int");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Strength")
                        .HasColumnType("int");

                    b.Property<int?>("Willpower")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            ID = "AIR-003",
                            CardName = "King Stefan - New Father",
                            Franchise = "Sleeping Beauty",
                            GemColor = 0,
                            Image_URL = "https://lorcana-api.com/images/king_stefan/new_father/king_stefan-new_father-large.png",
                            Ink = 5,
                            SetName = "Archazilia's Island"
                        },
                        new
                        {
                            ID = "ARI-001",
                            CardName = "Rhino - Motivational Speaker",
                            Franchise = "Bolt",
                            GemColor = 10,
                            Image_URL = "https://lorcana-api.com/images/rhino/motivational_speaker/rhino-motivational_speaker-large.png",
                            Ink = 5,
                            SetName = "Archazia's Island"
                        },
                        new
                        {
                            ID = "ARI-002",
                            CardName = "Perdita - Playful Mother",
                            Franchise = "101 Dalmatians",
                            GemColor = 9,
                            Image_URL = "https://lorcana-api.com/images/perdita/playful_mother/perdita-playful_mother-large.png",
                            Ink = 4,
                            SetName = "Archazia's Island"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
